// Code generated by go-swagger; DO NOT EDIT.

package sync_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSyncHierarchyParams creates a new SyncHierarchyParams object
// with the default values initialized.
func NewSyncHierarchyParams() *SyncHierarchyParams {

	return &SyncHierarchyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSyncHierarchyParamsWithTimeout creates a new SyncHierarchyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSyncHierarchyParamsWithTimeout(timeout time.Duration) *SyncHierarchyParams {

	return &SyncHierarchyParams{

		timeout: timeout,
	}
}

// NewSyncHierarchyParamsWithContext creates a new SyncHierarchyParams object
// with the default values initialized, and the ability to set a context for a request
func NewSyncHierarchyParamsWithContext(ctx context.Context) *SyncHierarchyParams {

	return &SyncHierarchyParams{

		Context: ctx,
	}
}

// NewSyncHierarchyParamsWithHTTPClient creates a new SyncHierarchyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSyncHierarchyParamsWithHTTPClient(client *http.Client) *SyncHierarchyParams {

	return &SyncHierarchyParams{
		HTTPClient: client,
	}
}

/*SyncHierarchyParams contains all the parameters to send to the API endpoint
for the sync hierarchy operation typically these are written to a http.Request
*/
type SyncHierarchyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sync hierarchy params
func (o *SyncHierarchyParams) WithTimeout(timeout time.Duration) *SyncHierarchyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sync hierarchy params
func (o *SyncHierarchyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sync hierarchy params
func (o *SyncHierarchyParams) WithContext(ctx context.Context) *SyncHierarchyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sync hierarchy params
func (o *SyncHierarchyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sync hierarchy params
func (o *SyncHierarchyParams) WithHTTPClient(client *http.Client) *SyncHierarchyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sync hierarchy params
func (o *SyncHierarchyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SyncHierarchyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
