// Code generated by go-swagger; DO NOT EDIT.

package sync_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Cyclops-Labs/cyclops-4-hpc.git/extensions/lexis/models"
)

// SyncHierarchyOKCode is the HTTP code returned for type SyncHierarchyOK
const SyncHierarchyOKCode int = 200

/*SyncHierarchyOK The load of data was completely successfully

swagger:response syncHierarchyOK
*/
type SyncHierarchyOK struct {
}

// NewSyncHierarchyOK creates SyncHierarchyOK with default headers values
func NewSyncHierarchyOK() *SyncHierarchyOK {

	return &SyncHierarchyOK{}
}

// WriteResponse to the client
func (o *SyncHierarchyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SyncHierarchyAcceptedCode is the HTTP code returned for type SyncHierarchyAccepted
const SyncHierarchyAcceptedCode int = 202

/*SyncHierarchyAccepted Operation done but there might have been some fails when adding part of the data

swagger:response syncHierarchyAccepted
*/
type SyncHierarchyAccepted struct {
}

// NewSyncHierarchyAccepted creates SyncHierarchyAccepted with default headers values
func NewSyncHierarchyAccepted() *SyncHierarchyAccepted {

	return &SyncHierarchyAccepted{}
}

// WriteResponse to the client
func (o *SyncHierarchyAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

// SyncHierarchyInternalServerErrorCode is the HTTP code returned for type SyncHierarchyInternalServerError
const SyncHierarchyInternalServerErrorCode int = 500

/*SyncHierarchyInternalServerError Something unexpected happend, error raised

swagger:response syncHierarchyInternalServerError
*/
type SyncHierarchyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSyncHierarchyInternalServerError creates SyncHierarchyInternalServerError with default headers values
func NewSyncHierarchyInternalServerError() *SyncHierarchyInternalServerError {

	return &SyncHierarchyInternalServerError{}
}

// WithPayload adds the payload to the sync hierarchy internal server error response
func (o *SyncHierarchyInternalServerError) WithPayload(payload *models.ErrorResponse) *SyncHierarchyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sync hierarchy internal server error response
func (o *SyncHierarchyInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SyncHierarchyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
