// Code generated by go-swagger; DO NOT EDIT.

package sync_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Cyclops-Labs/cyclops-4-hpc.git/extensions/lexis/models"
)

// SyncFlavorsOKCode is the HTTP code returned for type SyncFlavorsOK
const SyncFlavorsOKCode int = 200

/*SyncFlavorsOK The load of data was completely successfully

swagger:response syncFlavorsOK
*/
type SyncFlavorsOK struct {
}

// NewSyncFlavorsOK creates SyncFlavorsOK with default headers values
func NewSyncFlavorsOK() *SyncFlavorsOK {

	return &SyncFlavorsOK{}
}

// WriteResponse to the client
func (o *SyncFlavorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SyncFlavorsAcceptedCode is the HTTP code returned for type SyncFlavorsAccepted
const SyncFlavorsAcceptedCode int = 202

/*SyncFlavorsAccepted Operation done but there might have been some fails when adding part of the data

swagger:response syncFlavorsAccepted
*/
type SyncFlavorsAccepted struct {
}

// NewSyncFlavorsAccepted creates SyncFlavorsAccepted with default headers values
func NewSyncFlavorsAccepted() *SyncFlavorsAccepted {

	return &SyncFlavorsAccepted{}
}

// WriteResponse to the client
func (o *SyncFlavorsAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

// SyncFlavorsInternalServerErrorCode is the HTTP code returned for type SyncFlavorsInternalServerError
const SyncFlavorsInternalServerErrorCode int = 500

/*SyncFlavorsInternalServerError Something unexpected happend, error raised

swagger:response syncFlavorsInternalServerError
*/
type SyncFlavorsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSyncFlavorsInternalServerError creates SyncFlavorsInternalServerError with default headers values
func NewSyncFlavorsInternalServerError() *SyncFlavorsInternalServerError {

	return &SyncFlavorsInternalServerError{}
}

// WithPayload adds the payload to the sync flavors internal server error response
func (o *SyncFlavorsInternalServerError) WithPayload(payload *models.ErrorResponse) *SyncFlavorsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sync flavors internal server error response
func (o *SyncFlavorsInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SyncFlavorsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
