// Code generated by go-swagger; DO NOT EDIT.

package sync_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SyncFlavorsHandlerFunc turns a function with the right signature into a sync flavors handler
type SyncFlavorsHandlerFunc func(SyncFlavorsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SyncFlavorsHandlerFunc) Handle(params SyncFlavorsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SyncFlavorsHandler interface for that can handle valid sync flavors params
type SyncFlavorsHandler interface {
	Handle(SyncFlavorsParams, interface{}) middleware.Responder
}

// NewSyncFlavors creates a new http.Handler for the sync flavors operation
func NewSyncFlavors(ctx *middleware.Context, handler SyncFlavorsHandler) *SyncFlavors {
	return &SyncFlavors{Context: ctx, Handler: handler}
}

/*SyncFlavors swagger:route GET /sync/flavors syncManagement syncFlavors

Sync the OpenStack's flavors data in the system

*/
type SyncFlavors struct {
	Context *middleware.Context
	Handler SyncFlavorsHandler
}

func (o *SyncFlavors) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSyncFlavorsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
