// Code generated by go-swagger; DO NOT EDIT.

package sync_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SyncHierarchyHandlerFunc turns a function with the right signature into a sync hierarchy handler
type SyncHierarchyHandlerFunc func(SyncHierarchyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SyncHierarchyHandlerFunc) Handle(params SyncHierarchyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SyncHierarchyHandler interface for that can handle valid sync hierarchy params
type SyncHierarchyHandler interface {
	Handle(SyncHierarchyParams, interface{}) middleware.Responder
}

// NewSyncHierarchy creates a new http.Handler for the sync hierarchy operation
func NewSyncHierarchy(ctx *middleware.Context, handler SyncHierarchyHandler) *SyncHierarchy {
	return &SyncHierarchy{Context: ctx, Handler: handler}
}

/*SyncHierarchy swagger:route GET /sync/hierarchy syncManagement syncHierarchy

syncs all the organizations, projects, resources hierarchy from LEXIS

*/
type SyncHierarchy struct {
	Context *middleware.Context
	Handler SyncHierarchyHandler
}

func (o *SyncHierarchy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSyncHierarchyParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
