// Code generated by go-swagger; DO NOT EDIT.

// Package restapi LEXIS Extension Management API
//
//  An API which supports creation, deletion, listing etc of SERVICE
//  Schemes:
//    http
//    https
//  Host: localhost:8000
//  BasePath: /api/v0.1
//  Version: 0.1.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <diego@cyclops-labs.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
