// Code generated by go-swagger; DO NOT EDIT.

package trigger_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UDRRedoHandlerFunc turns a function with the right signature into a u d r redo handler
type UDRRedoHandlerFunc func(UDRRedoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UDRRedoHandlerFunc) Handle(params UDRRedoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UDRRedoHandler interface for that can handle valid u d r redo params
type UDRRedoHandler interface {
	Handle(UDRRedoParams, interface{}) middleware.Responder
}

// NewUDRRedo creates a new http.Handler for the u d r redo operation
func NewUDRRedo(ctx *middleware.Context, handler UDRRedoHandler) *UDRRedo {
	return &UDRRedo{Context: ctx, Handler: handler}
}

/*UDRRedo swagger:route GET /trigger/udrsredo triggerManagement uDRRedo

Redo of UDRs from the specific dates and with the specifc interval

*/
type UDRRedo struct {
	Context *middleware.Context
	Handler UDRRedoHandler
}

func (o *UDRRedo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUDRRedoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
